import { FormProps } from '@/components/form';
import OptionSettings from '@/domains/option-settings';

const items: FormProps<OptionSettings>['items'] = [
  {
    key: 'DayTimeSpeedRate',
    label: '白天流逝速度',
    type: 'slider',
    min: 0.1,
    max: 5,
    step: 0.1,
  },
  {
    key: 'NightTimeSpeedRate',
    label: '夜晚流逝速度',
    type: 'slider',
    min: 0.1,
    max: 5,
    step: 0.1,
  },
  {
    key: 'AutoSaveSpan',
    label: '自动保存间隔',
    type: 'select',
    options: [
      {
        label: '30秒',
        value: 30,
      },
      {
        label: '30分钟',
        value: 30 * 60,
      },
    ],
  },
  {
    key: 'ExpRate',
    label: '经验值倍率',
    type: 'slider',
    min: 0.1,
    max: 20,
    step: 0.1,
  },
  {
    key: 'PalCaptureRate',
    label: '捕获概率倍率',
    type: 'slider',
    min: 0.5,
    max: 2,
    step: 0.1,
  },
  {
    key: 'PalSpawnNumRate',
    label: '帕鲁出现数量倍率',
    description: '※提高帕鲁出现数量将导致游戏效能下降',
    type: 'slider',
    min: 0.5,
    max: 3,
    step: 0.1,
  },
  {
    key: 'PalDamageRateAttack',
    label: '帕鲁攻击伤害倍率',
    type: 'slider',
    min: 0.1,
    max: 5,
    step: 0.1,
  },
  {
    key: 'PalDamageRateDefense',
    label: '帕鲁承受伤害倍率',
    type: 'slider',
    min: 0.1,
    max: 5,
    step: 0.1,
  },
  {
    key: 'PalStomachDecreaceRate',
    label: '帕鲁饱食度降低倍率',
    type: 'slider',
    min: 0.1,
    max: 5,
    step: 0.1,
  },
  {
    key: 'PalStaminaDecreaceRate',
    label: '帕鲁耐力降低倍率',
    type: 'slider',
    min: 0.1,
    max: 5,
    step: 0.1,
  },
  {
    key: 'PalAutoHPRegeneRate',
    label: '帕鲁生命值自然回复倍率',
    type: 'slider',
    min: 0.1,
    max: 5,
    step: 0.1,
  },
  {
    key: 'PalAutoHpRegeneRateInSleep',
    label: '帕鲁睡眠时生命值回复倍率',
    description: '（帕鲁终端中的生命值回复倍率）',
    type: 'slider',
    min: 0.1,
    max: 5,
    step: 0.1,
  },
  {
    key: 'PlayerDamageRateAttack',
    label: '玩家攻击伤害倍率',
    type: 'slider',
    min: 0.1,
    max: 5,
    step: 0.1,
  },
  {
    key: 'PlayerDamageRateDefense',
    label: '玩家承受伤害倍率',
    type: 'slider',
    min: 0.1,
    max: 5,
    step: 0.1,
  },
  {
    key: 'PlayerStomachDecreaceRate',
    label: '玩家饱食度降低倍率',
    type: 'slider',
    min: 0.1,
    max: 5,
    step: 0.1,
  },
  {
    key: 'PlayerStaminaDecreaceRate',
    label: '玩家耐力降低倍率',
    type: 'slider',
    min: 0.1,
    max: 5,
    step: 0.1,
  },
  {
    key: 'PlayerAutoHPRegeneRate',
    label: '玩家生命值自然回复倍率',
    type: 'slider',
    min: 0.1,
    max: 5,
    step: 0.1,
  },
  {
    key: 'PlayerAutoHpRegeneRateInSleep',
    label: '玩家睡眠时生命值回复倍率',
    type: 'slider',
    min: 0.1,
    max: 5,
    step: 0.1,
  },
  {
    key: 'BuildObjectDamageRate',
    label: '对建筑伤害倍率',
    type: 'slider',
    min: 0.5,
    max: 3,
    step: 0.1,
  },
  {
    key: 'BuildObjectDeteriorationDamageRate',
    label: '建筑的劣化速度倍率',
    type: 'slider',
    min: 0,
    max: 10,
    step: 0.1,
  },
  {
    key: 'DropItemMaxNum',
    label: '世界内的掉落物上限',
    type: 'slider',
    min: 0,
    max: 5000,
    step: 0.1,
  },
  {
    key: 'CollectionDropRate',
    label: '道具采集量倍率',
    type: 'slider',
    min: 0.5,
    max: 3,
    step: 0.1,
  },
  {
    key: 'CollectionObjectHpRate',
    label: '可采集物品生命值倍率',
    type: 'slider',
    min: 0.5,
    max: 3,
    step: 0.1,
  },
  {
    key: 'CollectionObjectRespawnSpeedRate',
    label: '可采集物品刷新间隔',
    type: 'slider',
    min: 0.5,
    max: 3,
    step: 0.1,
  },
  {
    key: 'EnemyDropItemRate',
    label: '道具掉落量倍率',
    type: 'slider',
    min: 0.5,
    max: 3,
    step: 0.1,
  },
  {
    key: 'PalEggDefaultHatchingTime',
    label: '巨大蛋孵化所需时间（小时）',
    description: '※其他蛋也会相应改变孵化时间。',
    type: 'slider',
    min: 0,
    max: 240,
    step: 0.1,
  },
  {
    key: 'bEnableInvaderEnemy',
    label: '是否会发生袭击事件？',
    type: 'switch',
    labels: ['OFF', 'ON'],
  },
  {
    key: 'DeathPenalty',
    label: '死亡惩罚',
    type: 'select',
    options: [
      {
        value: 'None',
        label: '不掉落任何东西',
      },
      {
        value: 'Item',
        label: '掉落装备以外的道具',
      },
      {
        value: 'ItemAndEquipment',
        label: '掉落所有道具',
      },
      {
        value: 'All',
        label: '掉落所有道具及队伍内帕鲁',
      },
    ],
  },
  {
    key: 'GuildPlayerMaxNum',
    label: '公会人数上限',
    type: 'slider',
    min: 1,
    max: 100,
    step: 1,
  },
  {
    key: 'BaseCampMaxNumInGuild',
    label: '各公会的最大据点数',
    description: '※增加上限将会影响处理性能',
    type: 'slider',
    min: 3,
    max: 10,
    step: 1,
  },
  {
    key: 'BaseCampWorkerMaxNum',
    label: '据点工作帕鲁最大数',
    description: '※增加上限将会影响处理性能',
    type: 'slider',
    min: 1,
    max: 50,
    step: 1,
  },
];

export default items;
